-- ==========================================
-- SGC HRMS FULL 3NF NORMALIZED SCHEMA
-- ==========================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==========================================
-- 1. LOOKUP TABLES (1NF & 2NF Compliance)
-- ==========================================

CREATE TABLE IF NOT EXISTS departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT REFERENCES departments(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    UNIQUE(department_id, name)
);

CREATE TABLE IF NOT EXISTS employment_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL -- e.g., '5A', 'GFO LDN'
);

CREATE TABLE IF NOT EXISTS areas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id BIGINT REFERENCES regions(id),
    name TEXT NOT NULL,
    UNIQUE(region_id, name)
);

-- ==========================================
-- 2. EMPLOYEES (Core Entity)
-- ==========================================
CREATE TABLE IF NOT EXISTS employees (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name_english TEXT NOT NULL,
    email TEXT UNIQUE,
    mobile TEXT,
    position_id BIGINT REFERENCES positions(id),
    employment_status_id BIGINT REFERENCES employment_statuses(id),
    dob DATE,
    sex TEXT,
    blood_type TEXT,
    residence_address TEXT,
    residence_postal TEXT,
    photo_url TEXT,
    modular_docs JSONB DEFAULT '{}',
    school_name TEXT,
    educational TEXT,
    highest_level TEXT,
    major_subject TEXT,
    skills TEXT,
    work_history TEXT,
    csc_license TEXT,
    csc_date DATE,
    legal_34_40 TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 3. ER CASES
-- ==========================================
CREATE TABLE IF NOT EXISTS cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_name TEXT NOT NULL,
    area_id BIGINT REFERENCES areas(id),
    employee_id UUID REFERENCES employees(id), -- Normalized from text
    status TEXT DEFAULT 'OPEN',
    officer_id UUID REFERENCES employees(id), -- Normalized from text
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 4. SF INCIDENT REPORTS
-- ==========================================
CREATE TABLE IF NOT EXISTS ir_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id UUID REFERENCES employees(id), -- Normalized from text
    area_id BIGINT REFERENCES areas(id),
    status TEXT DEFAULT 'OPEN',
    sop_breakdown TEXT,
    baranggay_share TEXT,
    cash_amount NUMERIC(15,2),
    file_name TEXT,
    file_url TEXT,
    date_posted DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 5. L&D ASSIGNMENTS
-- ==========================================
CREATE TABLE IF NOT EXISTS ld_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID REFERENCES employees(id), -- Normalized from text
    report_type TEXT DEFAULT 'Daily Refresher',
    due_date DATE,
    priority TEXT DEFAULT 'Normal',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 6. L&D SUBMISSIONS
-- ==========================================
CREATE TABLE IF NOT EXISTS ld_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT REFERENCES ld_assignments(id) ON DELETE CASCADE,
    employee_id UUID REFERENCES employees(id), -- Normalized from text
    report_type TEXT,
    submission_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    file_url TEXT,
    status TEXT DEFAULT 'Verified'
);

-- ==========================================
-- 7. CASH ASSISTANCE LOGS
-- ==========================================
CREATE TABLE IF NOT EXISTS cash_assistance_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personnel_in_charge_id UUID REFERENCES employees(id), -- Normalized from text
    cash_assistance_type TEXT,
    payment_method TEXT DEFAULT 'Cash',
    amount NUMERIC(15,2),
    notes TEXT,
    status TEXT DEFAULT 'Pending',
    date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 8. ACTIVITY LOGS
-- ==========================================
CREATE TABLE IF NOT EXISTS activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    details TEXT,
    performed_by_id UUID REFERENCES employees(id), -- Normalized from text
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 9. TELLERS (Merged & Normalized)
-- ==========================================
-- Combines the redundant 'tellers' and 'tellersldn' tables into one.
CREATE TABLE IF NOT EXISTS tellers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID REFERENCES employees(id), -- Links to employee if available
    fullname TEXT, -- Used if the teller is external/not in employees table yet
    position_id BIGINT REFERENCES positions(id),
    status_id BIGINT REFERENCES employment_statuses(id),
    area_id BIGINT REFERENCES areas(id),
    outlet TEXT,
    contact_number TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 10. APP USERS
-- ==========================================
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY REFERENCES employees(id), -- 1:1 relationship with employees
    email TEXT UNIQUE NOT NULL,
    role TEXT DEFAULT 'User',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE departments, positions, employment_statuses, regions, areas, employees, cases, ir_cases, ld_assignments, ld_submissions, cash_assistance_logs, activity_logs, tellers, users;
