import React, { useState, useEffect } from 'react';
import { X, Moon, Sun, Database, Shield, LogOut, Type, Monitor } from 'lucide-react';
import { supabase } from '../supabaseClient';

const SystemConfigModal = ({ isOpen, onClose }) => {
  const [theme, setTheme] = useState(localStorage.getItem('hris-theme') || 'dark');
  const [fontSize, setFontSize] = useState(localStorage.getItem('hris-font-size') || 'medium');
  const [sbStatus, setSbStatus] = useState('Checking...');
  const [exporting, setExporting] = useState(false);

  const handleFullBackup = async () => {
    setExporting(true);
    try {
      const [
        { data: employees }, { data: cases }, { data: irCases },
        { data: ldAssignments }, { data: ldSubmissions }, { data: cashLogs },
        { data: activityLogs }, { data: tellers }, { data: tellersLDN },
        { data: departments }, { data: designations }
      ] = await Promise.all([
        supabase.from('employees').select('*').order('created_at', { ascending: true }),
        supabase.from('cases').select('*').order('created_at', { ascending: true }),
        supabase.from('ir_cases').select('*').order('created_at', { ascending: true }),
        supabase.from('ld_assignments').select('*').order('created_at', { ascending: true }),
        supabase.from('ld_submissions').select('*').order('submission_date', { ascending: true }),
        supabase.from('cash_assistance_logs').select('*').order('created_at', { ascending: true }),
        supabase.from('activity_logs').select('*').order('created_at', { ascending: true }),
        supabase.from('tellers').select('*').order('id', { ascending: true }),
        supabase.from('tellersldn').select('*').order('id', { ascending: true }),
        supabase.from('departments').select('*').order('id', { ascending: true }).catch(() => ({ data: [] })),
        supabase.from('designations').select('*').order('id', { ascending: true }).catch(() => ({ data: [] })),
      ]);

      const esc = (v) => (v != null && v !== '') ? `'${v.toString().replace(/'/g, "''")}'` : 'NULL';
      const escDef = (v) => (v != null && v !== '') ? `'${v.toString().replace(/'/g, "''")}'` : 'DEFAULT';
      const jsc = (v) => v ? `'${JSON.stringify(v).replace(/'/g, "''")}'` : "'{}'";
      const ts = new Date().toLocaleString();

      let sql = `-- SGC HRMS FULL BACKUP — Generated: ${ts}\n-- Tables: departments, designations, employees, cases, ir_cases, ld_assignments, ld_submissions,\n--         cash_assistance_logs, activity_logs, tellers, tellersldn\n\nCREATE EXTENSION IF NOT EXISTS "uuid-ossp";\n\n`;

      const tables = [
        {
          label: 'DEPARTMENTS', count: departments?.length ?? 0,
          ddl: `CREATE TABLE IF NOT EXISTS departments (\n    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    name TEXT UNIQUE NOT NULL\n);`,
          insert: departments?.length > 0 ? `INSERT INTO departments (name)\nVALUES\n` + departments.map(d => `(${esc(d.name)})`).join(',\n') + `\nON CONFLICT DO NOTHING;` : ''
        },
        {
          label: 'DESIGNATIONS', count: designations?.length ?? 0,
          ddl: `CREATE TABLE IF NOT EXISTS designations (\n    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    name TEXT UNIQUE NOT NULL\n);`,
          insert: designations?.length > 0 ? `INSERT INTO designations (name)\nVALUES\n` + designations.map(d => `(${esc(d.name)})`).join(',\n') + `\nON CONFLICT DO NOTHING;` : ''
        },
        {
          label: 'EMPLOYEES', count: employees?.length ?? 0,
          ddl: `CREATE TABLE IF NOT EXISTS employees (\n    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),\n    name_english TEXT, email TEXT, mobile TEXT, position TEXT, department TEXT,\n    designation_id BIGINT REFERENCES designations(id),\n    department_id BIGINT REFERENCES departments(id),\n    employment_status TEXT DEFAULT 'Probationary Status', dob DATE, sex TEXT,\n    blood_type TEXT, residence_address TEXT, residence_postal TEXT, photo_url TEXT,\n    modular_docs JSONB DEFAULT '{}', school_name TEXT, educational TEXT,\n    highest_level TEXT, major_subject TEXT, skills TEXT, work_history TEXT,\n    csc_license TEXT, csc_date DATE, legal_34_40 TEXT,\n    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL\n);`,
          insert: employees?.length > 0 ? `INSERT INTO employees (name_english,email,mobile,position,department,designation_id,department_id,employment_status,dob,sex,blood_type,residence_address,photo_url,modular_docs,school_name,educational,highest_level,major_subject,skills,work_history,csc_license,csc_date,legal_34_40,created_at)\nVALUES\n` + employees.map(e => `(${esc(e.name_english)},${esc(e.email)},${esc(e.mobile)},${esc(e.position)},${esc(e.department)},${e.designation_id??'NULL'},${e.department_id??'NULL'},${esc(e.employment_status)},${esc(e.dob)},${esc(e.sex)},${esc(e.blood_type)},${esc(e.residence_address)},${esc(e.photo_url)},${jsc(e.modular_docs)},${esc(e.school_name)},${esc(e.educational)},${esc(e.highest_level)},${esc(e.major_subject)},${esc(e.skills)},${esc(e.work_history)},${esc(e.csc_license)},${esc(e.csc_date)},${esc(e.legal_34_40)},${escDef(e.created_at)})`).join(',\n') + ';' : ''
        },
        {
          label: 'ER CASES', count: cases?.length ?? 0,
          ddl: `CREATE TABLE IF NOT EXISTS cases (\n    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    case_name TEXT, area TEXT, employees TEXT, status TEXT DEFAULT 'OPEN',\n    officer TEXT, notes TEXT,\n    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL\n);`,
          insert: cases?.length > 0 ? `INSERT INTO cases (case_name,area,employees,status,officer,notes,created_at)\nVALUES\n` + cases.map(c => `(${esc(c.case_name)},${esc(c.area)},${esc(c.employees)},${esc(c.status)},${esc(c.officer)},${esc(c.notes)},${escDef(c.created_at)})`).join(',\n') + ';' : ''
        },
        {
          label: 'SF INCIDENT REPORTS', count: irCases?.length ?? 0,
          ddl: `CREATE TABLE IF NOT EXISTS ir_cases (\n    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    agent_name TEXT, area TEXT, status TEXT DEFAULT 'OPEN', sop_breakdown TEXT,\n    baranggay_share TEXT, cash_amount NUMERIC, file_name TEXT, file_url TEXT,\n    date_posted DATE DEFAULT CURRENT_DATE,\n    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL\n);`,
          insert: irCases?.length > 0 ? `INSERT INTO ir_cases (agent_name,area,status,sop_breakdown,baranggay_share,cash_amount,file_name,file_url,date_posted,created_at)\nVALUES\n` + irCases.map(r => `(${esc(r.agent_name)},${esc(r.area)},${esc(r.status)},${esc(r.sop_breakdown)},${esc(r.baranggay_share)},${r.cash_amount??0},${esc(r.file_name)},${esc(r.file_url)},${escDef(r.date_posted)},${escDef(r.created_at)})`).join(',\n') + ';' : ''
        },
        {
          label: 'L&D ASSIGNMENTS', count: ldAssignments?.length ?? 0,
          ddl: `CREATE TABLE IF NOT EXISTS ld_assignments (\n    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    employee_name TEXT, report_type TEXT DEFAULT 'Daily Refresher', due_date DATE,\n    department TEXT, priority TEXT DEFAULT 'Normal',\n    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL\n);`,
          insert: ldAssignments?.length > 0 ? `INSERT INTO ld_assignments (employee_name,report_type,due_date,department,priority,created_at)\nVALUES\n` + ldAssignments.map(a => `(${esc(a.employee_name)},${esc(a.report_type)},${esc(a.due_date)},${esc(a.department)},${esc(a.priority)},${escDef(a.created_at)})`).join(',\n') + ';' : ''
        },
        {
          label: 'L&D SUBMISSIONS', count: ldSubmissions?.length ?? 0,
          ddl: `CREATE TABLE IF NOT EXISTS ld_submissions (\n    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    employee_name TEXT, report_type TEXT,\n    submission_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),\n    file_url TEXT, status TEXT DEFAULT 'Verified'\n);`,
          insert: ldSubmissions?.length > 0 ? `INSERT INTO ld_submissions (employee_name,report_type,submission_date,file_url,status)\nVALUES\n` + ldSubmissions.map(s => `(${esc(s.employee_name)},${esc(s.report_type)},${escDef(s.submission_date)},${esc(s.file_url)},${esc(s.status)})`).join(',\n') + ';' : ''
        },
        {
          label: 'CASH ASSISTANCE LOGS', count: cashLogs?.length ?? 0,
          ddl: `CREATE TABLE IF NOT EXISTS cash_assistance_logs (\n    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    personnel_in_charge TEXT, cash_assistance_type TEXT, payment_method TEXT DEFAULT 'Cash',\n    amount NUMERIC(15,2), notes TEXT, status TEXT DEFAULT 'Pending',\n    date DATE DEFAULT CURRENT_DATE,\n    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL\n);`,
          insert: cashLogs?.length > 0 ? `INSERT INTO cash_assistance_logs (personnel_in_charge,cash_assistance_type,payment_method,amount,notes,status,date,created_at)\nVALUES\n` + cashLogs.map(l => `(${esc(l.personnel_in_charge)},${esc(l.cash_assistance_type)},${esc(l.payment_method)},${l.amount??0},${esc(l.notes)},${esc(l.status)},${escDef(l.date)},${escDef(l.created_at)})`).join(',\n') + ';' : ''
        },
        {
          label: 'ACTIVITY LOGS', count: activityLogs?.length ?? 0,
          ddl: `CREATE TABLE IF NOT EXISTS activity_logs (\n    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    action TEXT, details TEXT, performed_by TEXT,\n    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL\n);`,
          insert: activityLogs?.length > 0 ? `INSERT INTO activity_logs (action,details,performed_by,created_at)\nVALUES\n` + activityLogs.map(l => `(${esc(l.action)},${esc(l.details)},${esc(l.performed_by)},${escDef(l.created_at)})`).join(',\n') + ';' : ''
        },
        {
          label: 'TELLERS — 5A', count: tellers?.length ?? 0,
          ddl: `CREATE TABLE IF NOT EXISTS tellers (\n    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    fullname TEXT, position TEXT DEFAULT 'Teller', status TEXT DEFAULT 'Active',\n    area TEXT DEFAULT '5A', outlet TEXT, contact_number TEXT,\n    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL\n);`,
          insert: tellers?.length > 0 ? `INSERT INTO tellers (fullname,position,status,area,outlet,contact_number,created_at)\nVALUES\n` + tellers.map(t => `(${esc(t.fullname)},${esc(t.position)},${esc(t.status)},${esc(t.area)},${esc(t.outlet)},${esc(t.contact_number)},${escDef(t.created_at)})`).join(',\n') + ';' : ''
        },
        {
          label: 'TELLERS — GFO LDN', count: tellersLDN?.length ?? 0,
          ddl: `CREATE TABLE IF NOT EXISTS tellersldn (\n    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    fullname TEXT, position TEXT DEFAULT 'Teller', status TEXT DEFAULT 'Active',\n    area TEXT DEFAULT 'GFO LDN', outlet TEXT, contact_number TEXT,\n    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL\n);`,
          insert: tellersLDN?.length > 0 ? `INSERT INTO tellersldn (fullname,position,status,area,outlet,contact_number,created_at)\nVALUES\n` + tellersLDN.map(t => `(${esc(t.fullname)},${esc(t.position)},${esc(t.status)},${esc(t.area)},${esc(t.outlet)},${esc(t.contact_number)},${escDef(t.created_at)})`).join(',\n') + ';' : ''
        },
      ];

      tables.forEach((t, i) => {
        sql += `-- ==========================================\n-- ${i+1}. ${t.label} (${t.count} records)\n-- ==========================================\n`;
        sql += t.ddl + '\n';
        if (t.insert) sql += t.insert + '\n';
        sql += '\n';
      });
      sql += `-- END OF BACKUP\n`;

      const blob = new Blob([sql], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `sgc_full_backup_${new Date().toISOString().split('T')[0]}.sql`;
      document.body.appendChild(a); a.click();
      document.body.removeChild(a); URL.revokeObjectURL(url);
    } catch (err) {
      alert('Backup failed: ' + err.message);
    } finally {
      setExporting(false);
    }
  };

  useEffect(() => {
    // Theme application
    if (theme === 'light') {
      document.body.classList.add('light-theme');
    } else {
      document.body.classList.remove('light-theme');
    }
    localStorage.setItem('hris-theme', theme);

    // Font size application
    const root = document.documentElement;
    if (fontSize === 'large') {
      root.style.fontSize = '18px';
    } else if (fontSize === 'small') {
      root.style.fontSize = '14px';
    } else {
      root.style.fontSize = '16px';
    }
    localStorage.setItem('hris-font-size', fontSize);
  }, [theme, fontSize]);

  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = 'hidden';
      // Check DB Status when modal opens
      supabase.auth.getSession().then(({ error }) => {
        setSbStatus(error ? 'Error Connecting' : 'Supabase Active');
      });
    } else {
      document.body.style.overflow = '';
    }
    return () => { document.body.style.overflow = ''; };
  }, [isOpen]);

  const handleLogout = async () => {
    await supabase.auth.signOut();
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div style={{
      position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.6)', backdropFilter: 'blur(12px)',
      zIndex: 9999, display: 'flex', alignItems: 'center', justifyContent: 'center',
      padding: '24px'
    }}>
      <div className="glass-panel animate-fade-in" style={{
        width: '100%', maxWidth: '600px', maxHeight: '90vh',
        display: 'flex', flexDirection: 'column', gap: '32px', padding: '40px',
        overflowY: 'auto', position: 'relative'
      }}>
        {/* Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <h2 style={{ display: 'flex', alignItems: 'center', gap: '12px', margin: 0, fontSize: '1.5rem' }}>
              <Settings size={28} className="text-gradient" />
              Engine Configuration
            </h2>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.9rem', marginTop: '4px' }}>
              Terminal & Interface parameters for the God-View suite.
            </p>
          </div>
          <button onClick={onClose} style={{ 
            background: 'rgba(255, 255, 255, 0.05)', border: 'none', color: 'var(--text-secondary)', 
            width: '36px', height: '36px', borderRadius: '50%', display: 'flex', 
            alignItems: 'center', justifyContent: 'center', cursor: 'pointer',
            transition: 'all 0.2s'
          }}
          onMouseOver={(e) => { e.currentTarget.style.background = 'rgba(255, 255, 255, 0.1)'; e.currentTarget.style.color = 'var(--text-primary)'; }}
          onMouseOut={(e) => { e.currentTarget.style.background = 'rgba(255, 255, 255, 0.05)'; e.currentTarget.style.color = 'var(--text-secondary)'; }} >
            <X size={20} />
          </button>
        </div>

        {/* Sections */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
          
          {/* Theme Selector */}
          <div>
            <h3 style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '2px', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Monitor size={16} /> Appearance Matrix
            </h3>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
              <div 
                onClick={() => setTheme('dark')}
                style={{
                  padding: '24px 16px', borderRadius: '16px', cursor: 'pointer', textAlign: 'center',
                  border: theme === 'dark' ? '2px solid var(--accent-blue)' : '2px solid var(--glass-border)',
                  background: theme === 'dark' ? 'rgba(88, 166, 255, 0.1)' : 'var(--bg-tertiary)',
                  color: theme === 'dark' ? 'var(--accent-blue)' : 'var(--text-primary)',
                  transition: 'all 0.3s ease'
                }}
              >
                <Moon size={32} style={{ margin: '0 auto 12px' }} />
                <div style={{ fontWeight: 'bold', fontSize: '1rem' }}>Cyber Dark</div>
                <div style={{ fontSize: '0.75rem', opacity: 0.7, marginTop: '4px' }}>Default Ops Mode</div>
              </div>

              <div 
                onClick={() => setTheme('light')}
                style={{
                  padding: '24px 16px', borderRadius: '16px', cursor: 'pointer', textAlign: 'center',
                  border: theme === 'light' ? '2px solid var(--accent-blue)' : '2px solid var(--glass-border)',
                  background: theme === 'light' ? 'rgba(88, 166, 255, 0.10)' : '#f6f8fa',
                  color: theme === 'light' ? 'var(--accent-blue)' : '#1f2328',
                  transition: 'all 0.3s ease'
                }}
              >
                <Sun size={32} style={{ margin: '0 auto 12px' }} />
                <div style={{ fontWeight: 'bold', fontSize: '1rem' }}>Clean Light</div>
                <div style={{ fontSize: '0.75rem', opacity: 0.7, marginTop: '4px' }}>High Contrast</div>
              </div>
            </div>
          </div>

          {/* Typography Selector */}
          <div>
            <h3 style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '2px', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Type size={16} /> Typography Scale
            </h3>
            <div style={{ display: 'flex', gap: '12px', background: 'var(--bg-primary)', padding: '6px', borderRadius: '12px', border: '1px solid var(--glass-border)' }}>
              {['small', 'medium', 'large'].map((size) => (
                <button
                  key={size}
                  onClick={() => setFontSize(size)}
                  style={{
                    flex: 1, padding: '10px', borderRadius: '8px', textTransform: 'capitalize', fontWeight: '600',
                    background: fontSize === size ? 'var(--accent-blue)' : 'transparent',
                    color: fontSize === size ? '#fff' : 'var(--text-secondary)',
                    transition: 'all 0.2s',
                    fontSize: size === 'small' ? '0.8rem' : size === 'large' ? '1rem' : '0.9rem'
                  }}
                >
                  {size}
                </button>
              ))}
            </div>
          </div>

          {/* System Telemetry */}
          <div style={{ background: 'var(--bg-tertiary)', padding: '24px', borderRadius: '20px', border: '1px solid var(--glass-border)' }}>
             <h3 style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '2px', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Shield size={16} /> Backend Connectivity
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <div style={{ width: '40px', height: '40px', borderRadius: '10px', background: 'rgba(88, 166, 255, 0.1)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <Database size={20} color="var(--accent-blue)" />
                  </div>
                  <div>
                    <div style={{ fontWeight: 'bold' }}>Supabase Cluster</div>
                    <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Region: ap-southeast-1</div>
                  </div>
                </div>
                <div style={{ 
                  padding: '6px 12px', borderRadius: '20px', fontSize: '0.75rem', fontWeight: 'bold',
                  background: sbStatus.includes('Active') ? 'rgba(63, 185, 80, 0.1)' : 'rgba(255, 123, 114, 0.1)',
                  color: sbStatus.includes('Active') ? 'var(--accent-green)' : 'var(--accent-red)',
                  border: `1px solid ${sbStatus.includes('Active') ? 'rgba(63, 185, 80, 0.2)' : 'rgba(255, 123, 114, 0.2)'}`
                }}>
                  {sbStatus}
                </div>
              </div>
            </div>
          </div>

        </div>

        {/* Data Portability */}
        <div style={{ background: 'var(--bg-tertiary)', padding: '24px', borderRadius: '20px', border: '1px solid var(--glass-border)' }}>
          <h3 style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '2px', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Database size={16} /> Data Portability
          </h3>
          <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', marginBottom: '16px' }}>
            Download all 9 tables as a single self-contained SQL backup file.
          </p>
          <button
            onClick={handleFullBackup}
            disabled={exporting}
            style={{
              width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px',
              padding: '14px', borderRadius: '12px', fontWeight: 'bold', fontSize: '0.9rem',
              background: exporting ? 'rgba(184,227,233,0.05)' : 'rgba(184,227,233,0.1)',
              border: '1px solid rgba(184,227,233,0.25)', color: 'var(--accent-blue)',
              cursor: exporting ? 'not-allowed' : 'pointer', transition: 'all 0.2s',
              opacity: exporting ? 0.7 : 1
            }}
            onMouseOver={(e) => { if (!exporting) e.currentTarget.style.background = 'rgba(184,227,233,0.18)'; }}
            onMouseOut={(e) => { if (!exporting) e.currentTarget.style.background = 'rgba(184,227,233,0.1)'; }}
          >
            <Database size={18} />
            {exporting ? 'Fetching all tables...' : 'Export Full Backup SQL'}
          </button>
        </div>

        {/* Footer Actions */}
        <div style={{ marginTop: 'auto', paddingTop: '24px', borderTop: '1px solid var(--glass-border)', display: 'flex', justifyContent: 'flex-end' }}>
          <button 
            onClick={handleLogout}
            style={{ 
              display: 'flex', alignItems: 'center', gap: '10px', padding: '12px 24px',
              borderRadius: '12px', background: 'rgba(255, 123, 114, 0.1)', color: 'var(--accent-red)',
              fontWeight: 'bold', fontSize: '0.9rem', cursor: 'pointer', transition: 'all 0.2s'
            }}
            onMouseOver={(e) => { e.currentTarget.style.background = 'var(--accent-red)'; e.currentTarget.style.color = '#fff'; }}
            onMouseOut={(e) => { e.currentTarget.style.background = 'rgba(255, 123, 114, 0.1)'; e.currentTarget.style.color = 'var(--accent-red)'; }}
          >
            <LogOut size={18} /> Seal Session & Sign Out
          </button>
        </div>
      </div>
    </div>
  );
};

export default SystemConfigModal;

function Settings(props) { return <svg xmlns="http://www.w3.org/2000/svg" width={props.size} height={props.size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}><path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.5a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z" /><circle cx="12" cy="12" r="3" /></svg>; }

